name: ReleaseCI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash scripts/release.sh ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}}

